### ISSUE TITLE
change log scan error message level

### ISSUE THREAD

**Issue by fishbar** [node-honeycomb/honeycomb-server#106]
log扫描得设置该处异常为 warn，error有点吓人

```
{ Error: EACCES: permission denied, scandir '/home/admin/honeycomb/logs/lost+found'
    at Object.fs.readdirSync (fs.js:904:18)
    at scanLogFiles (/home/admin/honeycomb/target/honeycomb/lib/admin/single_api/log.js:159:18)
```

**Comment by fishbar** [comment]
fixed
