### ISSUE TITLE
master exist when spawn ENOMEM

### ISSUE THREAD

**Issue by fishbar** [node-honeycomb/honeycomb-server#147]
```
MASTER server received uncaughtException, will shutdown. Error: spawn ENOMEM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at Child._spawn (/home/admin/honeycomb/target/honeycomb/lib/child.js:480:27)
    at Child._createChild (/home/admin/honeycomb/target/honeycomb/lib/child.js:662:24)
    at Child._create (/home/admin/honeycomb/target/honeycomb/lib/child.js:536:12)
    at Timeout._onTimeout (/home/admin/honeycomb/target/honeycomb/lib/child.js:830:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
internal/child_process.js:323
```

**Comment by fishbar** [comment]
fixed
